<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>1.0.0</VersionPrefix>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <PackageId>VILLAN3LL3.NLog.Slack</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Description>An NLog target for Slack (forked from https://github.com/nmbro/NTRPRS.NLog.Slack)</Description>
    <RepositoryUrl>https://github.com/VILLAN3LL3/VILLAN3LL3.NLog.Slack</RepositoryUrl>
    <PackageProjectUrl>https://github.com/VILLAN3LL3/VILLAN3LL3.NLog.Slack</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.2.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
